name: Npm publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install
        run: npm install

      - name: Test 🧪
        run: npm run nx run use-mutative:test:production

      - name: Build 🔧
        run: npm run nx run use-mutative:build

      - name: Publish 🔧
        run: npm publish ./dist/libs/use-mutative
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          CI: true